catalog_controllers:
    resource: ../src/Catalog/Infrastructure/Http/Controller/
    type: attribute

shared_controllers:
    resource: ../src/Shared/Infrastructure/Http/Controller/
    type: attribute
